language: ruby
rvm:
  - 2.3.3

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - jekyll
env:
  global:
  - GH_REF: github.com/RedL0tus/RedL0tus.github.io.git

sudo: false

after_script:
  - cd ./_site
  - git init
  - git config user.name "RedL0tus"
  - git config user.email "i@ikay.work"
  - git add -A
  - git commit -m "Update blog."
  - git push --force "https://${GITHUB_TOKEN}@${GH_REF}" master:master
