# Site settings
title: Untitled
description: Untitled
author: KayMW
email: i@ikay.work
baseurl: "" # the subpath of your site, e.g. /blog
url: https://v2bv.net # the base hostname & protocol for your site
twitter_username: KayTheSF
github_username:  RedL0tus

disqus_shortname: sth-1

# Build settings
include: [_pages]
markdown: kramdown
permalink: :year/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
  - amp-jekyll # Accelerated Mobile Pages
  - jekyll-tidy

# AMP Settings
ampdir: /amp
enable_amp: true

exclude: [vendor]

# Google Analytics
google_analytics: UA-97897080-1
